"""Full-text quote check for the closest prior work (abstracts do not state these results): fetch the arXiv HTML, strip markup
(MathML is rendered as spaced text, e.g. 'S 4'), and require the quote verbatim. Output: expressivity/results/body_quotes.json.
  python expressivity/scripts/body_quotes.py"""
import html, json, re, urllib.request

QUOTES = {
    "deltaproduct": ("2502.10297", "Unexpectedly, S 4 and A 5 can extrapolate robustly using only n h = 2 despite the theorem suggesting 3 and 4, respectively."),
    "deltaproduct-so3": ("2502.10297", "This efficiency arises from their isomorphism to subgroups of SO ⁡ ( 3 , ℝ ) , i.e. the group of 3D rotations"),
    "howe-law": ("2609.18966", "the minimal n h that length-generalizes equals the maximal generator reflection length rank ⁡ ( I − P ) in the representation pinned by the task format (parity 1, S 4 3, A 5 / S 5 4)"),
    "howe-format": ("2609.18966", "S 4 (transposition + 4-cycle), A 5 (3-cycle + 5-cycle; all-even), S 5 (transposition + 5-cycle; non-solvable)"),
    "rwkv7-swaps": ("2503.14456", "RWKV-7 can, by Lemma 2 , solve the problem of tracking swaps on five elements."),
    "grazzi-cd": ("2411.12537", "every n × n orthogonal matrix can be written as a product of n reflections, due to the Cartan–Dieudonné Theorem"),
    # added after the novelty check (expressivity/novelty.md)
    "ckda-thm4": ("2609.24797", "We rule out one-layer S 5 tracking for CKDA and DeltaProduct k ( k ≤ 3 ) with non-expansive transitions and finite reachability"),
    "ckda-four": ("2609.24797", "this proves that four is the minimum number of Householder transformations needed for single-layer Gated DeltaProduct tracking of S 5 under these assumptions."),
    "ckda-compression": ("2609.24797", "We first choose a word whose linear part has minimum Frobenius norm and repeat it until it acts as a projection without changing the decoded value."),
    "ckda-decoder": ("2609.24797", "Tracking does not require a faithful representation: a many-to-one decoder can map distinct hidden states to the same group element, and the input transitions need not themselves form a representation."),
    "ckda-so3": ("2609.24797", "A single CKDA layer (one head) tracks every finite group isomorphic to a subgroup of S ​ O ​ ( 3 ) ."),
    "martino-singh": ("1804.05089", "We say that a group $G$ is generated (resp. strictly generated) in codimension $k$ if it is generated by its elements that fix point-wise a subspace of codimension at most $k$ (resp. precisely $k$)."),
    "lange-mikhailova": ("1509.06922", "We survey the existing parts of a classification of finite groups generated by orthogonal transformations in a finite-dimensional Euclidean space whose fixed point subspace has codimension one or two and extend it to a complete classification."),
    "geck-malle": ("math/0311012", "reﬂections necessarily have order 2"),
}


def text(aid):
    """arXiv HTML full text; falls back to the abstract page and to the PDF (pdftotext) for papers without HTML."""
    out = ""
    for url in (f"https://arxiv.org/html/{aid}", f"https://arxiv.org/abs/{aid}"):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "hacknation-ai-lab/0.1 (quote check)"})
            out += " " + urllib.request.urlopen(req, timeout=60).read().decode("utf-8", "replace")
        except Exception:
            pass
    try:
        import subprocess, tempfile
        req = urllib.request.Request(f"https://arxiv.org/pdf/{aid}", headers={"User-Agent": "hacknation-ai-lab/0.1 (quote check)"})
        with tempfile.NamedTemporaryFile(suffix=".pdf") as f:
            f.write(urllib.request.urlopen(req, timeout=90).read()); f.flush()
            out += " " + subprocess.run(["pdftotext", f.name, "-"], capture_output=True, text=True).stdout
    except Exception:
        pass
    s = out
    s = re.sub(r"<(script|style|annotation)[^>]*>.*?</\1>", " ", s, flags=re.S); s = re.sub(r"<[^>]+>", " ", s)
    return re.sub(r"\s+", " ", html.unescape(s))


cache, out = {}, {}
for key, (aid, q) in QUOTES.items():
    if aid not in cache: cache[aid] = text(aid)
    out[key] = {"id": f"arXiv:{aid}", "quote": q, "verified": q in cache[aid]}
    print(key, out[key]["verified"])
json.dump(out, open("expressivity/results/body_quotes.json", "w"), indent=1, ensure_ascii=False)
