const fs=require('fs'),vm=require('vm'),assert=require('assert');
const file=require('path').join(__dirname,'few_distance.html'),html=fs.readFileSync(file,'utf8');
const payload=html.match(/<script id="data" type="application\/json">([\s\S]*?)<\/script>/)[1],code=html.match(/<script>\n([\s\S]*?)<\/script>/)[1];
function node(){return{children:[],dataset:{},style:{},value:'',textContent:'',classList:{toggle(){}},setAttribute(k,v){this[k]=v;},append(...xs){this.children.push(...xs);},replaceChildren(...xs){this.children=xs;}};}
const elements={};for(const id of ['data','case','plot','palette','scope','geometry-title','count','equation','old','new','facts','source','coordinates','verification','attack-result','geometry-caption','animate','clear','verify','attack'])elements[id]=node();
elements.data.textContent=payload;elements.case.value='1';let interval=null;
const document={getElementById:id=>elements[id],createElement:node,createElementNS:node,querySelectorAll:()=>elements.palette.children};
const context=vm.createContext({document,BigInt,Number,Math,JSON,Set,Map,Error,setInterval:fn=>{interval=fn;return 1;},clearInterval:()=>{interval=null;}});vm.runInContext(code,context);
const results=[];for(const id of ['1','0']){elements.case.value=id;vm.runInContext('select()',context);let n=id==='1'?111:81,k=id==='1'?41:31;assert.equal(elements.plot.children.length,n);assert.equal(elements.palette.children.length,k);assert.match(elements.verification.textContent,/PASS/);elements.attack.onclick();assert.match(elements['attack-result'].textContent,/Rejected: duplicate point/);elements.animate.onclick();assert(interval);for(let i=0;i<k;i++)interval();assert.equal(vm.runInContext('active',context),1);elements.animate.onclick();assert.equal(interval,null);elements.palette.children[k-1].onclick();let expected=id==='1'?6:4;assert.equal(elements.plot.children.filter(x=>x.stroke==='#ffc475').length,expected);results.push({case:n,classes:k,highlighted_pairs:expected,duplicate_rejected:true,tour_wrap_passed:true,status:elements.verification.textContent});}
console.log(JSON.stringify({passed:true,scope:'real generated JavaScript run with minimal DOM mock; screenshot checks separate',results},null,2));
