"""Exact constructions of realisations (H, pi, lifts t_s, rho) for word problems (G, Sigma).

A construction returns a dict {sigma (permutation tuple): matrix (exact)} giving rho(t_sigma) for each letter; the covering group
H is the matrix group these generate and pi is read off by the verifier's closure (realisation.verify). Constructions:
  perm          permutation matrices of G's own action (rational)
  so3           G as a rotation group in SO(3): A4 (tetrahedral), S4 (octahedral), A5 (icosahedral, over Q(sqrt 5))
  planar        Z_m / dihedral D_m in 2 dimensions (companion basis over Q(2 cos(2 pi/m)))
  count         abelian count cover: one coordinate block per letter (reflection for involutions, planar rotation otherwise)
  twist=<set>   multiply rho(sigma) by -1 for the letters in <set> (involutions | all | none): a lift to G x Z2
"""
from .algebra import (Field, mat, eye, mmul, mT, mkey, closure, porder, pmul, pid, msub, rank)


def perm_matrix(F, p):
    n = len(p)
    return tuple(tuple(F.one if p[j] == i else F.zero for j in range(n)) for i in range(n))


def _matrix_closure(gens, cap=100000):
    I = eye(gens[0][0][0].F, len(gens[0])); seen = {mkey(I): I}; frontier = [I]
    while frontier:
        nxt = []
        for X in frontier:
            for g in gens:
                Y = mmul(g, X); k = mkey(Y)
                if k not in seen:
                    seen[k] = Y; nxt.append(Y)
                    if len(seen) > cap: raise OverflowError("matrix group too large")
        frontier = nxt
    return seen


def iso_from_generators(G, mgens):
    """Find an isomorphism from the matrix group <mgens> onto G that maps each matrix generator to some element of G.
    Returns {g in G: matrix}. Brute force over images with matching orders, checked by a consistent pair closure."""
    import itertools
    Mgrp = _matrix_closure(mgens)
    if len(Mgrp) != G.order: return None
    orders = [_morder(m) for m in mgens]
    cands = [[g for g in G.elements if porder(g) == o] for o in orders]
    for imgs in itertools.product(*cands):
        if len(closure(list(imgs), G.n)) != G.order: continue
        ok, table = _pair_closure(G, list(imgs), mgens)
        if ok and len(table) == G.order: return table
    return None


def _morder(M):
    I = eye(M[0][0].F, len(M)); X = M; k = 1
    while X != I:
        X = mmul(M, X); k += 1
        if k > 10000: raise OverflowError
    return k


def _pair_closure(G, pg, mg):
    e = G.e; I = eye(mg[0][0][0].F, len(mg[0]))
    table = {e: I}; back = {mkey(I): e}; frontier = [e]
    while frontier:
        nxt = []
        for x in frontier:
            for p, m in zip(pg, mg):
                y = pmul(p, x); Y = mmul(m, table[x])
                if y in table:
                    if mkey(table[y]) != mkey(Y): return False, table
                else:
                    if mkey(Y) in back: return False, table
                    table[y] = Y; back[mkey(Y)] = y; nxt.append(y)
        frontier = nxt
    return True, table


def so3_generators(G):
    name = G.name
    if name == "A4":
        F = Field(1)
        return [mat(F, [[0, 0, 1], [1, 0, 0], [0, 1, 0]]), mat(F, [[1, 0, 0], [0, -1, 0], [0, 0, -1]])]
    if name == "S4":
        F = Field(1)
        return [mat(F, [[0, 0, 1], [1, 0, 0], [0, 1, 0]]), mat(F, [[0, -1, 0], [1, 0, 0], [0, 0, 1]])]
    if name == "A5":
        F = Field(5); phi = F.gen() + 1; h = F(1) / 2      # phi = 1 + 2 cos(2 pi/5) = (1 + sqrt5)/2
        b = [[h, -phi * h, (phi - 1) * h], [phi * h, (phi - 1) * h, -h], [(phi - 1) * h, h, phi * h]]
        return [mat(F, [[0, 0, 1], [1, 0, 0], [0, 1, 0]]), tuple(tuple(x for x in r) for r in b)]
    raise ValueError(f"no SO(3) model stored for {name}")


def planar_rotation(F, m, j=1):
    """Rotation by 2 pi j / m in the companion basis (e, R e): [[0, -1], [1, 2 cos(2 pi j/m)]] over K_N (m | N)."""
    tc = F.two_cos(j * (F.N // m))
    return ((F.zero, -F.one), (F.one, tc))


def construct(G, sigma, rep, twist="none"):
    """Return {s: matrix} for the letters s in sigma."""
    if rep == "perm":
        F = Field(1); R = {s: perm_matrix(F, s) for s in sigma}
    elif rep == "so3":
        table = iso_from_generators(G, so3_generators(G))
        if table is None: raise ValueError("SO(3) model not isomorphic")
        R = {s: table[s] for s in sigma}
    elif rep == "planar":
        # G cyclic of order m (generated by G.gens[0]) or dihedral D_m (gens: rotation, reflection)
        rot_g = max(G.gens, key=porder) if len(G.gens) == 1 or porder(G.gens[0]) == 2 else G.gens[0]
        others = [g for g in G.gens if g != rot_g]
        m = porder(rot_g); F = Field(m if m > 2 else 1)
        rot = planar_rotation(F, m) if m > 2 else ((-F.one, F.zero), (F.zero, F.one))
        mg = [rot]
        pg = [rot_g]
        if others:                                     # dihedral: the second generator is a reflection (order 2)
            mg.append(((F.one, F.gen() if m > 2 else F.zero), (F.zero, -F.one)))   # reflection in the companion basis: e -> e, Re -> c e - Re
            pg.append(others[0])
        ok, table = _pair_closure(G, pg, mg)
        if not ok or len(table) != G.order: raise ValueError("planar model inconsistent")
        R = {s: table[s] for s in sigma}
    elif rep == "count":
        if not G.is_abelian(): raise ValueError("count cover needs an abelian group")
        from math import lcm
        ords = [porder(s) for s in sigma]; N = lcm(*[o for o in ords if o > 2] or [1]); F = Field(N)
        blocks = [1 if o == 2 else 2 for o in ords]; d = sum(blocks); R = {}; off = 0
        for s, o, b in zip(sigma, ords, blocks):
            M = [[F.one if i == j else F.zero for j in range(d)] for i in range(d)]
            if b == 1: M[off][off] = -F.one
            else:
                r = planar_rotation(F, o)
                for i in range(2):
                    for j in range(2): M[off + i][off + j] = r[i][j]
            R[s] = tuple(tuple(x for x in row) for row in M); off += b
    else:
        raise ValueError(f"unknown construction {rep}")
    if twist != "none":
        flip = {s for s in sigma if (twist == "all" or (twist == "involutions" and porder(s) == 2))}
        R = {s: (tuple(tuple(-x for x in r) for r in M) if s in flip else M) for s, M in R.items()}
    return R
